### ISSUE TITLE
[PBI] H3 total coverage

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#11]
be sure the H3 covers the entire country (little south-west shape is currently missing)

**Comment by pierreleripoll** [comment]
See https://github.com/uber/geojson2h3#:~:text=If%20the%20polygon%20is%20small%20in%20comparison%20with%20the%20chosen%20resolution%2C%20there%20may%20be%20no%20cell%20whose%20center%20lies%20within%20it%2C%20resulting%20in%20an%20empty%20set.%20To%20fall%20back%20to%20a%20single%20H3%20cell%20representing%20the%20centroid%20of%20the%20polygon%20in%20this%20case%2C%20use%20the%20ensureOutput%20option.
