### ISSUE TITLE
[BUG] Multiple assets emit different content to the same filename index.html

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

make install
make run

results in : 

![image](https://user-images.githubusercontent.com/97044425/207283830-290b53f3-b4d1-433a-a89e-e97857275af4.png)

```
Conflict: Multiple assets emit different content to the same filename index.html

ERROR in Conflict: Multiple assets emit different content to the same filename index.html

webpack compiled with 1 error
```

### Expected Behavior

To be able to run the application with error

### Steps To Reproduce

clone repo
make install
make run

### Environment

```markdown
- OS: windows
```

**Comment by pierreleripoll** [comment]
I did the steps to reproduce on linux and no problem 
![image](https://user-images.githubusercontent.com/20055338/207302709-07be5ef2-ba9f-42bb-9327-4645fca426c7.png)
Maybe it's linked to os ? Though it's weird... Will retry on windows later

**Comment by pierreleripoll** [comment]
Ok I saw the problem ! You're using make run inside frontend directory, I will delete this makefile because the correct one is in the root folder

**Comment by pierreleripoll** [comment]
I close this issue because I tried to reproduce it on windows but it took me too much time, I think it's not worth it since we have a test version deployed on epfl's server !
