### ISSUE TITLE
[PBI] UX App layout CSS

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#34]
@pierreleripoll does a first draft
@meschultheiss gives his feedback

**Comment by pierreleripoll** [comment]
Closing as duplicate of #40

**Comment by regislon** [comment]
To be done : 
- [ ] transport modes in radio buttons
- [ ] Add presenation text + website content
- [ ] add simple mode
- [ ] remove one location search bar
- [ ] zoom out to see entirely Switzerland

**Comment by pierreleripoll** [comment]
@regislon since this issue is closed I copy your comment to open issue #40
