### ISSUE TITLE
[PBI] Add real dataset

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#37]
This dataset will process early april -> project will be paused.

**Comment by meschultheiss** [comment]
Two files for h3 and poly.
One column for each mode of transport and "all"
Values are percentages
Pickle files compression={'method': 'gzip'}

[demand.zip](https://github.com/EPFL-ENAC/LASUR-swiss-proximity/files/11856851/demand.zip)

**Comment by meschultheiss** [comment]
Two files for h3 and poly.
Columns {1,2,3,4,5} are the diversity coefficient 
Dataframe to be groupby(poi_kind) depending on UI selection
Pickle files compression={'method': 'gzip'}

[supply.zip](https://github.com/EPFL-ENAC/LASUR-swiss-proximity/files/11856864/supply.zip)

**Comment by meschultheiss** [comment]
txt file to convert hex to poly.

[hex_to_taz.pkl.zip](https://github.com/EPFL-ENAC/LASUR-swiss-proximity/files/11856868/hex_to_taz.pkl.zip)
