### ISSUE TITLE
[FEATURE] Template / first design web app

### ISSUE THREAD

**Issue by meschultheiss** [EPFL-ENAC/LASUR-swiss-proximity#40]
### Describe the solution you would like.

On peut partir sur le template de ALICE. Le bandeau de gauche de gestion de filtre est bien, et le bandeau de titre aussi.

Aussi, certains éléments me semblent important de conserver:
- Le popup au chargement de la page
- Le frame légende
- Le mode full-screen
- Les onglets
- Les liens vers d’autres pages statiques html

Au niveau du design:
- limiter le zoom-out à la suisse
- peut-on mettre le layer hexagones sous le layer lacs?
- le fond de carte est-il modifiable?

**Comment by pierreleripoll** [comment]
To be done : 
- [ ] transport modes in radio buttons
- [ ] Add presenation text + website content
- [ ] add simple mode
- [ ] remove one location search bar
- [ ] zoom out to see entirely Switzerland
- [ ] start splash screen manually

_Originally posted by @regislon in https://github.com/EPFL-ENAC/LASUR-swiss-proximity/issues/34#issuecomment-1418790273_
